### PR TITLE
Geometry convert fixes

### LINKED ISSUE #195: Geometry: Polyline conversion bug
#### Description:

Conversion of BHoM polyline -> Dynamo curve is missing:

image

Would be great to resolve it in 3.1 milestone as it is really annoying for the end users.

#### Test file(s):

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FDynamo%5FToolkit%2FDynamo%5FToolkit%2DIssue195%2DPolylineConversionBug).

### LINKED ISSUE #196: Geometry: Bidirectional conversion of polylines
#### Description:
In opposition to BHoM, Dynamo does not support polylines as a distinct type: they are mere `Autodesk.DesignScript.Geometry.PolyCurves` with linear segments. As a consequence, all polylines get converted to `BH.oM.Geometry.PolyCurve`, which causes ambiguity and is very problematic while trying to build a BHoM workflow (where many features support only `BH.oM.Geometry.Polyline`).

I am wondering if it would not be better to force the convert to check if all segments of Dynamo polycurve are linear, and if so, then convert to `BH.oM.Geometry.Polyline` instead of `BH.oM.Geometry.PolyCurve`. A bit of an overhead, but BHoM <-> Dynamo geometry handling would become much more intuitive for the end user.

@al-fisher @rwemay what do you think?

### LINKED ISSUE #227: Stack overflow on surface convert
#### Description:

Happens due to the lines below calling each other.

https://github.com/BHoM/Dynamo_Toolkit/blob/cc54ddf17699075e542be01f506fa8480a824ac9/Dynamo20/Dynamo_Engine/Convert/FromDesignScript.cs#L182-L185

#### Test file(s):

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FDynamo%5FToolkit%2FDynamo%5FToolkit%2DIssue227%2DSurfaceConvert) - **it will crash Revit on run**

### LINKED ISSUE #230: Dynamo_Toolkit: line vs two-vertex curve bug
#### Description:

When a line is considered a two-vertex curve, convert fails.

#### Test file(s):

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FDynamo%5FToolkit%2FDynamo%5FToolkit%2DIssue230%2DTwoVertexCurve)

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #195 
Closes #196
Closes #227 
Closes #230

Also covers some parts of #224, but this needs further work.

### Test files

[#195 #196](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FDynamo%5FToolkit%2FDynamo%5FToolkit%2DIssue195%2DPolylineConversionBug)
[#227](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FDynamo%5FToolkit%2FDynamo%5FToolkit%2DIssue227%2DSurfaceConvert)
[#230](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FDynamo%5FToolkit%2FDynamo%5FToolkit%2DIssue230%2DTwoVertexCurve)

### Changelog

- Conversion between Dynamo `Polycurve` and BHoM `Polyline` has been unlocked
- Conversion between Dynamo two-node `Curve` and `BHoM` Line has been unlocked
- Conversion of Dynamo `Surface` to BHoM has been fixed to avoid stack overflow

### CODE REVIEW

File: Dynamo20/Dynamo_Engine/Convert/FromDesignScript.cs [hunk 1]
```diff
@@ -118,63 +125,98 @@ public static BHG.Vector FromDesignScript(this ADG.Vector designScriptVec)
...
+
+            // Force convert to BH.oM.Geometry.Polyline if the curve consists of linear segments only.
+            if (curves.Count != 0 && curves.All(x => x is BHG.Line))
+            {
+                List<BHG.Point> controlPoints = new List<BHG.Point> { ((BHG.Line)curves[0]).Start };
+                controlPoints.AddRange(curves.Select(x => ((BHG.Line)x).End));
+                return new BHG.Polyline { ControlPoints = controlPoints };
+            }
+            else
+                return Geometry.Create.PolyCurve(polyCurve.Curves().Select(x => x.IFromDesignScript()));
```
Comment (adecler) [inline Dynamo20/Dynamo_Engine/Convert/FromDesignScript.cs:219]: super minor but should reuse the `curves` created above.
